/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Certification as PrismaCertification,
  Component as PrismaComponent,
  Contract as PrismaContract,
  Vendor as PrismaVendor,
} from "@prisma/client";

export class CertificationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CertificationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.certification.count(args);
  }

  async certifications(
    args: Prisma.CertificationFindManyArgs
  ): Promise<PrismaCertification[]> {
    return this.prisma.certification.findMany(args);
  }
  async certification(
    args: Prisma.CertificationFindUniqueArgs
  ): Promise<PrismaCertification | null> {
    return this.prisma.certification.findUnique(args);
  }
  async createCertification(
    args: Prisma.CertificationCreateArgs
  ): Promise<PrismaCertification> {
    return this.prisma.certification.create(args);
  }
  async updateCertification(
    args: Prisma.CertificationUpdateArgs
  ): Promise<PrismaCertification> {
    return this.prisma.certification.update(args);
  }
  async deleteCertification(
    args: Prisma.CertificationDeleteArgs
  ): Promise<PrismaCertification> {
    return this.prisma.certification.delete(args);
  }

  async findComponents(
    parentId: string,
    args: Prisma.ComponentFindManyArgs
  ): Promise<PrismaComponent[]> {
    return this.prisma.certification
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .components(args);
  }

  async findContracts(
    parentId: string,
    args: Prisma.ContractFindManyArgs
  ): Promise<PrismaContract[]> {
    return this.prisma.certification
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .contracts(args);
  }

  async getVendor(parentId: string): Promise<PrismaVendor | null> {
    return this.prisma.certification
      .findUnique({
        where: { id: parentId },
      })
      .vendor();
  }
}
