/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumCertificationAction } from "./EnumCertificationAction";
import {
  IsEnum,
  IsOptional,
  IsDate,
  ValidateNested,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { ComponentUpdateManyWithoutCertificationsInput } from "./ComponentUpdateManyWithoutCertificationsInput";
import { ContractUpdateManyWithoutCertificationsInput } from "./ContractUpdateManyWithoutCertificationsInput";
import { EnumCertificationSystemType } from "./EnumCertificationSystemType";
import { EnumCertificationTypeField } from "./EnumCertificationTypeField";
import { VendorWhereUniqueInput } from "../../vendor/base/VendorWhereUniqueInput";

@InputType()
class CertificationUpdateInput {
  @ApiProperty({
    required: false,
    enum: EnumCertificationAction,
  })
  @IsEnum(EnumCertificationAction)
  @IsOptional()
  @Field(() => EnumCertificationAction, {
    nullable: true,
  })
  action?: "Approved" | "Pending" | "Denied" | "Other";

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  applicationDate?: Date;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  certificationDate?: Date;

  @ApiProperty({
    required: false,
    type: () => ComponentUpdateManyWithoutCertificationsInput,
  })
  @ValidateNested()
  @Type(() => ComponentUpdateManyWithoutCertificationsInput)
  @IsOptional()
  @Field(() => ComponentUpdateManyWithoutCertificationsInput, {
    nullable: true,
  })
  components?: ComponentUpdateManyWithoutCertificationsInput;

  @ApiProperty({
    required: false,
    type: () => ContractUpdateManyWithoutCertificationsInput,
  })
  @ValidateNested()
  @Type(() => ContractUpdateManyWithoutCertificationsInput)
  @IsOptional()
  @Field(() => ContractUpdateManyWithoutCertificationsInput, {
    nullable: true,
  })
  contracts?: ContractUpdateManyWithoutCertificationsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  expirationDate?: Date;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  federalCertDate?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  federalCertNumber?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  modelNumber?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  notes?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumCertificationSystemType,
  })
  @IsEnum(EnumCertificationSystemType)
  @IsOptional()
  @Field(() => EnumCertificationSystemType, {
    nullable: true,
  })
  systemType?:
    | "Dre"
    | "OpScan"
    | "DreOpscan"
    | "PcLaptopBased"
    | "TabletBased"
    | "CustomHardwareBased"
    | "Other";

  @ApiProperty({
    required: false,
    enum: EnumCertificationTypeField,
  })
  @IsEnum(EnumCertificationTypeField)
  @IsOptional()
  @Field(() => EnumCertificationTypeField, {
    nullable: true,
  })
  typeField?:
    | "Certification"
    | "Reevaluation"
    | "Renewal"
    | "Recertification"
    | "Other";

  @ApiProperty({
    required: false,
    type: () => VendorWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => VendorWhereUniqueInput)
  @IsOptional()
  @Field(() => VendorWhereUniqueInput, {
    nullable: true,
  })
  vendor?: VendorWhereUniqueInput | null;
}

export { CertificationUpdateInput as CertificationUpdateInput };
