/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ComponentService } from "../component.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ComponentCreateInput } from "./ComponentCreateInput";
import { Component } from "./Component";
import { ComponentFindManyArgs } from "./ComponentFindManyArgs";
import { ComponentWhereUniqueInput } from "./ComponentWhereUniqueInput";
import { ComponentUpdateInput } from "./ComponentUpdateInput";
import { InventoryUnitFindManyArgs } from "../../inventoryUnit/base/InventoryUnitFindManyArgs";
import { InventoryUnit } from "../../inventoryUnit/base/InventoryUnit";
import { InventoryUnitWhereUniqueInput } from "../../inventoryUnit/base/InventoryUnitWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ComponentControllerBase {
  constructor(
    protected readonly service: ComponentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Component })
  @nestAccessControl.UseRoles({
    resource: "Component",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createComponent(
    @common.Body() data: ComponentCreateInput
  ): Promise<Component> {
    return await this.service.createComponent({
      data: {
        ...data,

        certification: data.certification
          ? {
              connect: data.certification,
            }
          : undefined,
      },
      select: {
        certification: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        name: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Component] })
  @ApiNestedQuery(ComponentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Component",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async components(@common.Req() request: Request): Promise<Component[]> {
    const args = plainToClass(ComponentFindManyArgs, request.query);
    return this.service.components({
      ...args,
      select: {
        certification: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        name: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Component })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Component",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async component(
    @common.Param() params: ComponentWhereUniqueInput
  ): Promise<Component | null> {
    const result = await this.service.component({
      where: params,
      select: {
        certification: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        name: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Component })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Component",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateComponent(
    @common.Param() params: ComponentWhereUniqueInput,
    @common.Body() data: ComponentUpdateInput
  ): Promise<Component | null> {
    try {
      return await this.service.updateComponent({
        where: params,
        data: {
          ...data,

          certification: data.certification
            ? {
                connect: data.certification,
              }
            : undefined,
        },
        select: {
          certification: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          id: true,
          name: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Component })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Component",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteComponent(
    @common.Param() params: ComponentWhereUniqueInput
  ): Promise<Component | null> {
    try {
      return await this.service.deleteComponent({
        where: params,
        select: {
          certification: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          id: true,
          name: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/inventoryUnits")
  @ApiNestedQuery(InventoryUnitFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "InventoryUnit",
    action: "read",
    possession: "any",
  })
  async findInventoryUnits(
    @common.Req() request: Request,
    @common.Param() params: ComponentWhereUniqueInput
  ): Promise<InventoryUnit[]> {
    const query = plainToClass(InventoryUnitFindManyArgs, request.query);
    const results = await this.service.findInventoryUnits(params.id, {
      ...query,
      select: {
        acquisitionDate: true,

        component: {
          select: {
            id: true,
          },
        },

        condition: true,
        createdAt: true,

        disposition: {
          select: {
            id: true,
          },
        },

        expense: {
          select: {
            id: true,
          },
        },

        id: true,
        notes: true,
        serialNumber: true,

        storageLocation: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        use: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/inventoryUnits")
  @nestAccessControl.UseRoles({
    resource: "Component",
    action: "update",
    possession: "any",
  })
  async connectInventoryUnits(
    @common.Param() params: ComponentWhereUniqueInput,
    @common.Body() body: InventoryUnitWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inventoryUnits: {
        connect: body,
      },
    };
    await this.service.updateComponent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/inventoryUnits")
  @nestAccessControl.UseRoles({
    resource: "Component",
    action: "update",
    possession: "any",
  })
  async updateInventoryUnits(
    @common.Param() params: ComponentWhereUniqueInput,
    @common.Body() body: InventoryUnitWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inventoryUnits: {
        set: body,
      },
    };
    await this.service.updateComponent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/inventoryUnits")
  @nestAccessControl.UseRoles({
    resource: "Component",
    action: "update",
    possession: "any",
  })
  async disconnectInventoryUnits(
    @common.Param() params: ComponentWhereUniqueInput,
    @common.Body() body: InventoryUnitWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inventoryUnits: {
        disconnect: body,
      },
    };
    await this.service.updateComponent({
      where: params,
      data,
      select: { id: true },
    });
  }
}
