/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Certification } from "../../certification/base/Certification";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { InventoryUnit } from "../../inventoryUnit/base/InventoryUnit";
import { EnumComponentTypeField } from "./EnumComponentTypeField";

@ObjectType()
class Component {
  @ApiProperty({
    required: false,
    type: () => Certification,
  })
  @ValidateNested()
  @Type(() => Certification)
  @IsOptional()
  certification?: Certification | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  description!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: () => [InventoryUnit],
  })
  @ValidateNested()
  @Type(() => InventoryUnit)
  @IsOptional()
  inventoryUnits?: Array<InventoryUnit>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: true,
    enum: EnumComponentTypeField,
  })
  @IsEnum(EnumComponentTypeField)
  @Field(() => EnumComponentTypeField, {
    nullable: true,
  })
  typeField?:
    | "Dre"
    | "OpScan"
    | "Bmd"
    | "Vvpat"
    | "Cots"
    | "Other"
    | "Hardware"
    | "Software"
    | "Peripheral";

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Component as Component };
