/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ExpenseService } from "../expense.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ExpenseCreateInput } from "./ExpenseCreateInput";
import { Expense } from "./Expense";
import { ExpenseFindManyArgs } from "./ExpenseFindManyArgs";
import { ExpenseWhereUniqueInput } from "./ExpenseWhereUniqueInput";
import { ExpenseUpdateInput } from "./ExpenseUpdateInput";
import { InventoryUnitFindManyArgs } from "../../inventoryUnit/base/InventoryUnitFindManyArgs";
import { InventoryUnit } from "../../inventoryUnit/base/InventoryUnit";
import { InventoryUnitWhereUniqueInput } from "../../inventoryUnit/base/InventoryUnitWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ExpenseControllerBase {
  constructor(
    protected readonly service: ExpenseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Expense })
  @nestAccessControl.UseRoles({
    resource: "Expense",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createExpense(
    @common.Body() data: ExpenseCreateInput
  ): Promise<Expense> {
    return await this.service.createExpense({
      data: {
        ...data,

        contract: data.contract
          ? {
              connect: data.contract,
            }
          : undefined,

        county: data.county
          ? {
              connect: data.county,
            }
          : undefined,

        vendor: data.vendor
          ? {
              connect: data.vendor,
            }
          : undefined,
      },
      select: {
        amount: true,

        contract: {
          select: {
            id: true,
          },
        },

        county: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        fund: true,
        id: true,
        name: true,
        notes: true,
        owner: true,
        updatedAt: true,

        vendor: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Expense] })
  @ApiNestedQuery(ExpenseFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Expense",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async expenses(@common.Req() request: Request): Promise<Expense[]> {
    const args = plainToClass(ExpenseFindManyArgs, request.query);
    return this.service.expenses({
      ...args,
      select: {
        amount: true,

        contract: {
          select: {
            id: true,
          },
        },

        county: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        fund: true,
        id: true,
        name: true,
        notes: true,
        owner: true,
        updatedAt: true,

        vendor: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Expense })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Expense",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async expense(
    @common.Param() params: ExpenseWhereUniqueInput
  ): Promise<Expense | null> {
    const result = await this.service.expense({
      where: params,
      select: {
        amount: true,

        contract: {
          select: {
            id: true,
          },
        },

        county: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        fund: true,
        id: true,
        name: true,
        notes: true,
        owner: true,
        updatedAt: true,

        vendor: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Expense })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Expense",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateExpense(
    @common.Param() params: ExpenseWhereUniqueInput,
    @common.Body() data: ExpenseUpdateInput
  ): Promise<Expense | null> {
    try {
      return await this.service.updateExpense({
        where: params,
        data: {
          ...data,

          contract: data.contract
            ? {
                connect: data.contract,
              }
            : undefined,

          county: data.county
            ? {
                connect: data.county,
              }
            : undefined,

          vendor: data.vendor
            ? {
                connect: data.vendor,
              }
            : undefined,
        },
        select: {
          amount: true,

          contract: {
            select: {
              id: true,
            },
          },

          county: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          fund: true,
          id: true,
          name: true,
          notes: true,
          owner: true,
          updatedAt: true,

          vendor: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Expense })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Expense",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteExpense(
    @common.Param() params: ExpenseWhereUniqueInput
  ): Promise<Expense | null> {
    try {
      return await this.service.deleteExpense({
        where: params,
        select: {
          amount: true,

          contract: {
            select: {
              id: true,
            },
          },

          county: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          fund: true,
          id: true,
          name: true,
          notes: true,
          owner: true,
          updatedAt: true,

          vendor: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/inventoryUnits")
  @ApiNestedQuery(InventoryUnitFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "InventoryUnit",
    action: "read",
    possession: "any",
  })
  async findInventoryUnits(
    @common.Req() request: Request,
    @common.Param() params: ExpenseWhereUniqueInput
  ): Promise<InventoryUnit[]> {
    const query = plainToClass(InventoryUnitFindManyArgs, request.query);
    const results = await this.service.findInventoryUnits(params.id, {
      ...query,
      select: {
        acquisitionDate: true,

        component: {
          select: {
            id: true,
          },
        },

        condition: true,
        createdAt: true,

        disposition: {
          select: {
            id: true,
          },
        },

        expense: {
          select: {
            id: true,
          },
        },

        id: true,
        notes: true,
        serialNumber: true,

        storageLocation: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        use: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/inventoryUnits")
  @nestAccessControl.UseRoles({
    resource: "Expense",
    action: "update",
    possession: "any",
  })
  async connectInventoryUnits(
    @common.Param() params: ExpenseWhereUniqueInput,
    @common.Body() body: InventoryUnitWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inventoryUnits: {
        connect: body,
      },
    };
    await this.service.updateExpense({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/inventoryUnits")
  @nestAccessControl.UseRoles({
    resource: "Expense",
    action: "update",
    possession: "any",
  })
  async updateInventoryUnits(
    @common.Param() params: ExpenseWhereUniqueInput,
    @common.Body() body: InventoryUnitWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inventoryUnits: {
        set: body,
      },
    };
    await this.service.updateExpense({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/inventoryUnits")
  @nestAccessControl.UseRoles({
    resource: "Expense",
    action: "update",
    possession: "any",
  })
  async disconnectInventoryUnits(
    @common.Param() params: ExpenseWhereUniqueInput,
    @common.Body() body: InventoryUnitWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inventoryUnits: {
        disconnect: body,
      },
    };
    await this.service.updateExpense({
      where: params,
      data,
      select: { id: true },
    });
  }
}
