/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  ValidateNested,
  IsOptional,
  IsEnum,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { ComponentWhereUniqueInput } from "../../component/base/ComponentWhereUniqueInput";
import { EnumInventoryUnitCondition } from "./EnumInventoryUnitCondition";
import { DispositionWhereUniqueInput } from "../../disposition/base/DispositionWhereUniqueInput";
import { ExpenseWhereUniqueInput } from "../../expense/base/ExpenseWhereUniqueInput";
import { StorageLocationWhereUniqueInput } from "../../storageLocation/base/StorageLocationWhereUniqueInput";
import { EnumInventoryUnitUse } from "./EnumInventoryUnitUse";

@InputType()
class InventoryUnitCreateInput {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  acquisitionDate!: Date;

  @ApiProperty({
    required: false,
    type: () => ComponentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ComponentWhereUniqueInput)
  @IsOptional()
  @Field(() => ComponentWhereUniqueInput, {
    nullable: true,
  })
  component?: ComponentWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    enum: EnumInventoryUnitCondition,
  })
  @IsEnum(EnumInventoryUnitCondition)
  @Field(() => EnumInventoryUnitCondition)
  condition!: "New" | "Excellent" | "Good" | "Worn" | "Damaged" | "Unusable";

  @ApiProperty({
    required: false,
    type: () => DispositionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DispositionWhereUniqueInput)
  @IsOptional()
  @Field(() => DispositionWhereUniqueInput, {
    nullable: true,
  })
  disposition?: DispositionWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ExpenseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ExpenseWhereUniqueInput)
  @IsOptional()
  @Field(() => ExpenseWhereUniqueInput, {
    nullable: true,
  })
  expense?: ExpenseWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  notes?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  serialNumber!: string;

  @ApiProperty({
    required: false,
    type: () => StorageLocationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => StorageLocationWhereUniqueInput)
  @IsOptional()
  @Field(() => StorageLocationWhereUniqueInput, {
    nullable: true,
  })
  storageLocation?: StorageLocationWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    enum: EnumInventoryUnitUse,
  })
  @IsEnum(EnumInventoryUnitUse)
  @Field(() => EnumInventoryUnitUse)
  use!: "Active" | "Spare" | "Display" | "Other" | "Inactive";
}

export { InventoryUnitCreateInput as InventoryUnitCreateInput };
